// Generated by CoffeeScript 1.7.1
[
  {
    name: 'MetOcean Public Website',
    dns: {
      'metocean.co.nz': '173.230.243.117',
      'www.metocean.co.nz': '173.230.243.117'
    },
    ping: ['173.230.243.117'],
    http: [
      {
        'http://metocean.co.nz/': 301
      }, 'http://www.metocean.co.nz/'
    ]
  }
];
